backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"

collections:
  - name: "articles"
    label: "Artikel"
    files:
      - name: "article_data"
        label: "Data Artikel"
        file: "data/articles.json"
        fields:
          - label: "Daftar Artikel"
            name: "articles"
            widget: "list"
            fields:
              - label: "ID"
                name: "id"
                widget: "number"
              - label: "Judul"
                name: "title"
                widget: "string"
              - label: "Penulis"
                name: "author"
                widget: "string"
              - label: "Tanggal"
                name: "date"
                widget: "string"
              - label: "Thumbnail Class"
                name: "thumb"
                widget: "select"
                options:
                  - "thumb-1"
                  - "thumb-2"
                  - "thumb-3"
              - label: "Konten HTML"
                name: "content"
                widget: "markdown"
